# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ethical Hacking
email: admin@prannay.com
description: > # this means to ignore newlines until "baseurl:"
  The official blog of team `team` of IIT Kanpur and their usual hackings and musings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prannayk.github.io" # the base hostname & protocol for your site
github_username:  prannayk

# Build settings
markdown: kramdown
